package com.myretail.product.model;

// Generated Oct 5, 2015 5:25:33 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProdPrice generated by hbm2java
 */
@Entity
@Table(name = "prod_price")
public class ProductPrice implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = -3387135262926474679L;

	@Column(name = "price", unique = false, nullable = false, columnDefinition="Decimal(10,2) default '0.0'")
	private Double price;
	
	@Column(name = "product_id", unique = true, nullable = false)
	private Long productId;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;
	
	
	public Double getPrice()
	{
		return price;
	}
	public void setPrice(Double price)
	{
		this.price = price;
	}
	public Long getProductId()
	{
		return productId;
	}
	public void setProductId(Long productId)
	{
		this.productId = productId;
	}
	public Long getId()
	{
		return id;
	}
	public void setId(Long id)
	{
		this.id = id;
	}
	
	
}
